### ISSUE TITLE
还是不懂怎么导入阅读啊😭😭

### ISSUE THREAD

**Issue by huhuhuhuk** [litcc/tts-server#10]
直接复制那段链接也不行 
大佬求助🧎‍♀️🧎‍♂️

**Comment by ZYFDroid** [comment]
什么导入阅读

**Comment by litcc** [comment]
https://github.com/litcc/tts-server/raw/main/help.md
这个帮助看了没？

**Comment by ZYFDroid** [comment]
我有个想法，要不要把生成阅读软件导入字符串的功能给做到前端里去

**Comment by litcc** [comment]
> 我有个想法，要不要把生成阅读软件导入字符串的功能给做到前端里去

可以有

**Comment by huhuhuhuk** [comment]
> https://github.com/litcc/tts-server/raw/main/help.md
> 这个帮助看了没？

看了 看了两小时 没看明白 😭😭

**Comment by huhuhuhuk** [comment]
> https://github.com/litcc/tts-server/raw/main/help.md
> 这个帮助看了没？

哪个链接复制上去也不中用

**Comment by litcc** [comment]
> > https://github.com/litcc/tts-server/raw/main/help.md
> > 这个帮助看了没？
> 
> 哪个链接复制上去也不中用

链接肯定需要手动修改了，改成你自己对应的ip，
你是有特殊需求还是苹果手机？必须得使用这个程序么?如果没用特殊需求其实你完全可以使用android app(https://github.com/ag2s20150909/TTS)直接解决，方便简单

**Comment by huhuhuhuk** [comment]
> > > https://github.com/litcc/tts-server/raw/main/help.md
> > > 这个帮助看了没？
> > 
> > 
> > 哪个链接复制上去也不中用
> 
> 链接肯定需要手动修改了，改成你自己对应的ip， 你是有特殊需求还是苹果手机？必须得使用这个程序么?如果没用特殊需求其实你完全可以使用android app(https://github.com/ag2s20150909/TTS) 直接解决，方便简单

ios 安卓app有 想在ios上听

**Comment by huhuhuhuk** [comment]
> > > https://github.com/litcc/tts-server/raw/main/help.md
> > > 这个帮助看了没？
> > 
> > 
> > 哪个链接复制上去也不中用
> 
> 链接肯定需要手动修改了，改成你自己对应的ip， 你是有特殊需求还是苹果手机？必须得使用这个程序么?如果没用特殊需求其实你完全可以使用android app(https://github.com/ag2s20150909/TTS) 直接解决，方便简单

ios有办法弄吗

**Comment by litcc** [comment]
> ios有办法弄吗

可以，你是在服务器搭建还是路由器搭建，还是win电脑直接运行呢？

**Comment by huhuhuhuk** [comment]
> > ios有办法弄吗
> 
> 可以，你是在服务器搭建还是路由器搭建，还是win电脑直接运行呢？

win电脑的话是不是要一直开着

**Comment by litcc** [comment]
> win电脑的话是不是要一直开着

是的

**Comment by huhuhuhuk** [comment]
> > win电脑的话是不是要一直开着
> 
> 是的



> > win电脑的话是不是要一直开着
> 
> 是的

具体如何操作呢 就按文章里的来 显示启动api服务失败

**Comment by ZYFDroid** [comment]
建议qq聊聊，我这边邮箱正在响个不停

**Comment by huhuhuhuk** [comment]
> > win电脑的话是不是要一直开着
> 
> 是的

校园网ip怎么看

**Comment by huhuhuhuk** [comment]
> 建议qq聊聊，我这边邮箱正在响个不停

不好意思。我加您？

**Comment by huhuhuhuk** [comment]
win的我挂着后台了也获取api了 改了ip导入阅读 显示获取朗读音频放回数据为空
 http://ip:端口/tts-ms,{
                    "method": "POST",
                    "body": {
                        "informant": "zh-CN-YunxiNeural",
                        "style": "general",
                        "rate": {{ speakSpeed / 6 }},
                        "text": "{{java.encodeURI(speakText)}}"
                    }
                }

**Comment by ZYFDroid** [comment]
![image](https://user-images.githubusercontent.com/39429452/162002219-a89cf38d-e9d6-460f-bad3-309ce43b74ff.png)
我试出来了

**Comment by huhuhuhuk** [comment]
> 建议：
> 
> * 正确填写你的IP地址和端口号
> * 关闭windows的防火墙，或者将网络配置文件设置为 专用

成功了 出声了😿😿😿

**Comment by litcc** [comment]
> 成功了 出声了😿😿😿

建议将解决方案分享出来
