### ISSUE TITLE
ms_tts.rs执行出错程序结束

### ISSUE THREAD

**Issue by rogueme** [litcc/tts-server#13]
系统是centos8,启动tts-server后,使用阅读播放后程序就异常退出了,日志如下:
`2022-06-24 23:49:04.435718398 [tts_server::ms_tts] event-bus-thread 140052308014848 INFO - 连接至内陆服务器
2022-06-24 23:49:04.440898864 [tts_server::ms_tts] event-bus-thread 140052308014848 INFO - 连接至 "202.89.233.102"
thread 'event-bus-thread' panicked at 'called `Option::unwrap()` on a `None` value', src/ms_tts.rs:287:92
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`
偶尔能读一次,但基本都是这个错误日志

**Comment by rogueme** [comment]
发现问题了,这里只支持audio开头的,其他的都出错,是不是不支持解码导致的?

**Comment by litcc** [comment]
修好了，试试0.2.3版本

**Comment by rogueme** [comment]
@litcc 好的，晚点回去试试

**Comment by rogueme** [comment]
> 修好了，试试0.2.3版本

试了下,程序我会执行出错结束了,但raw的貌似还有问题,没有声音,下载下来也播放不了

**Comment by litcc** [comment]
emmm，有错误日志没？我这边测试确实是正常了

**Comment by ZYFDroid** [comment]
raw格式当然不能直接播放

**Comment by ZYFDroid** [comment]
要播放就得用audio开头的

**Comment by litcc** [comment]
我这边实际测试，除了raw的无法播放，其他所有格式都可以在网页播放，至于您说出现程序报错退出的情况，我这边并没有出现过

**Comment by rogueme** [comment]
> emmm，有错误日志没？我这边测试确实是正常了

日志是正常的,网站播放没反应,其他开头正常播放,阅读上朗读日志是朗读错误

**Comment by litcc** [comment]
使用raw格式是有什么特殊需求吗？网页暂时不支持直接播放，阅读应该也不支持，我对于这些编码格式了解的不是特别多，数据都是从ms那边拿到的，如果播放不了，可能需要特殊的解码器吧，你可以使用其他非raw编码格式

**Comment by ZYFDroid** [comment]
raw格式是不能直接播放的。raw格式是未封装过的PCM数据，除非手动读取然后喂给声卡。audio开头的都包含了解码音频所需要的必要信息

**Comment by ZYFDroid** [comment]
或许可以试试把raw格式的编码选项移除

**Comment by litcc** [comment]
去掉也不是不行，但是有没有可能，有部分音频处理人员或者其他人员可能会用到呢?

**Comment by rogueme** [comment]
语速貌似也有bug吧,无论加多少结果都是固定一个数的,减会变一个数,但同样不管减多少得到的结果也是同一个数,乘除也一样,我直接给数值50,日志里的rete还是200的数

**Comment by litcc** [comment]
![image](https://user-images.githubusercontent.com/13202561/175796361-4aa28c89-cc09-4488-92aa-dff1815d855a.png)

我这边实测语速与音调都可以使用参数控制，不会出现固定一个值

**Comment by rogueme** [comment]
> ![image](https://user-images.githubusercontent.com/13202561/175796361-4aa28c89-cc09-4488-92aa-dff1815d855a.png)
> 
> 我这边实测语速与音调都可以使用参数控制，不会出现固定一个值
> 
> 您可以参考 https://github.com/litcc/tts-server/blob/main/help.md 文档里面 语速与音调的参数范围，这个不是直接传ssml用的数值

好吧,我的锅,还以为直接给的,所以给的数都比较大
