### ISSUE TITLE
云野，晓晨，还有ogg-24khz-16bit-mono-opus都不能朗读了，提示unsupported voice

### ISSUE THREAD

**Issue by o0HalfLife0o** [litcc/tts-server#14]
我一开始以为微软把这几个像语音风格一样都封了，但是隔壁tts这个软件又都正常可用，

**Comment by ZYFDroid** [comment]
隔壁用的可能是微软demo页面的接口。这里用的是Microsoft Edge的大声朗读接口

**Comment by ZYFDroid** [comment]
准确来说是edge的大声朗读不支持这些东西，可以考虑像隔壁一样改用到微软demo页面的接口

**Comment by litcc** [comment]
我抽空测试一下，我这边也没有一直用，所以什么时候用不了并不能及时了解
