### ISSUE TITLE
[TODO] 关于解决”好像只有美国的节点能用“的问题

### ISSUE THREAD

**Issue by edmund-zhao** [litcc/tts-server#15]
根据微软官方文档说明 [REST API](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/rest-text-to-speech#prebuilt-neural-voices)

不同地区创建的Token是不通用的，需要使用对应地区的Token，访问对应地区的API

例如日本东部地区
![image](https://user-images.githubusercontent.com/53864204/187724118-d1256a3c-cb56-4985-b047-bd1d5459bf44.png)

则需要调用这个接口
`https://japaneast.tts.speech.microsoft.com/cognitiveservices/v1`

**Comment by litcc** [comment]
当前master分支的话，是使用edge的免费接口（爬的），后面版本也会持续支持，不过能使用的参数和能连接的服务器就只有那么几个了；可能后续就没有连接指定服务器的功能了；

然后目前使用官方的Api已经基本开发完了了（api token和地域是需要配置的参数），并且把项目相关结构重构了一遍，剩下的也就是数据的发送接收处理了，不过我打算等一个依赖库 clap 更新到 4.0的时候再push代码

![image](https://user-images.githubusercontent.com/13202561/187805989-19438875-d93c-475e-b0ea-e07e04d03343.png)
