### ISSUE TITLE
Edge浏览器 大声朗读 云健

### ISSUE THREAD

**Issue by yaoxin1588** [litcc/tts-server#16]
Edge浏览器 新的发言人 Yunjian 云健 在tts-server中输入YunjianNeural后还是晓晓朗读，不知是什么原因？

**Comment by litcc** [comment]
下个版本修复这个问题，因为项目改动的地方比较多，新版本支持了多个渠道（edge，官网宣传页，以及使用apikey），所以还没改完，可能会稍微晚几天，可能回到中秋之后

**Comment by yaoxin1588** [comment]
好的,非常期待!

**Comment by litcc** [comment]
![image](https://user-images.githubusercontent.com/13202561/191773667-baed69d8-29aa-4792-8cf3-119495ad4d71.png)

```
{
    "text":"云健快说话",
    "informant":"zh-CN-YunjianNeural"
}
```

如图，参数需要时这样哦 zh-CN-YunjianNeural
