### ISSUE TITLE
源码中那些个节点IP从何而来？

### ISSUE THREAD

**Issue by jing332** [litcc/tts-server#17]
看了下源码，貌似是把 speech.platform.bing.com 解析到自定义的IP上,可我用Golang写了个类似的，并不能成功连接。
所以请问，这个功能作用何在？

**Comment by litcc** [comment]
好久没维护那个ip列表了，不确定是否还支持，是用来用国内ip加速用的，下个版本可能会去掉这个功能，或者说在以后的版本再支持上，新版本在next分支，改动相对来说比较多
