### ISSUE TITLE
似乎不能用很久了

### ISSUE THREAD

**Issue by conphi** [litcc/tts-server#18]
尝试在三个不同服务器上部署，都不能用了，大家都还能用吗？

**Comment by litcc** [comment]
确实暂时用不了，伙计可以先使用其他替代工具，我正在努力完成下一个版本，完成后会解决当前的问题，但是可能需要点时间，目前改动在next分支，改动比较大，新增了几个接口

**Comment by conphi** [comment]
@jing332 现在用的浏览器插件下载的音频的，你分享的两个都只有中文，而且不能下载音频。
@litcc 我最喜欢你这个版本了，能tts大量文字，而且能下载高质量音频，期待中；现在只能用浏览器插件了，可是只能每次下载少量文字tts的音频。
下面是我用的
https://greasyfork.org/zh-CN/scripts/444347-azure-speech-download

**Comment by conphi** [comment]
> 

@jing332 你推荐的这个非常棒！

**Comment by litcc** [comment]
基本功能已经修复，WebUI 还需要再等等，这个 issue 先关了，有问题的话可以再开
