### ISSUE TITLE
定时一个小时左右会结束

### ISSUE THREAD

**Issue by enterlet** [litcc/tts-server#22]
晚上定时2个小时发现基本上1个小时就会断
看了下阅读的日志，是提示连续错误5次后自动停止
电脑上用的是
`tts-server.exe --listen-port 20222 --do-not-update-speakers-list --close-official-subscribe-api --close-official-preview-api`
手机上用的是
```
http://192.168.xx.xx:20222/api/tts-ms-edge,{
        "method": "POST",
        "body": {
            "informant": "zh-CN-XiaoxiaoNeural",
            "rate": {{ 0.88}},
            "text": "{{java.encodeURI(speakText).replace('+','%20')}}"
        }
    }
```
手机上阅读的日志提示错误
![Screenshot_2022-11-04-06-28-08-680_io legado app release](https://user-images.githubusercontent.com/21063655/199967129-1a678b85-dcf8-4803-8c33-b8d69e4d5069.jpg)
电脑上也没提示错误，就是到这里就没了
<img width="833" alt="2022-11-04_073930" src="https://user-images.githubusercontent.com/21063655/199967154-3b80d4e7-8a77-449c-b341-6d0e325bb19a.png">

**Comment by litcc** [comment]
emmm错误信息有点少
试试通过debug模式启动，并写入日志到文件，然后反馈日志文件

**Comment by enterlet** [comment]
[tts.log](https://github.com/litcc/tts-server/files/9942508/tts.log)
不知道还有啥能提供的了
我的手机是MIUI，阅读的省电策略已经是无限制了

**Comment by ZYFDroid** [comment]
MIUI手机断开之后用其它手机或者电脑还能访问服务器吗？
- 如果能：
    - 可能是MIUI激进的省电策略在搞鬼。毕竟国内安卓ROM魔改程度
    - 解决方案：使用一些工具例如 tts-vue 预先把小说转换成音频再播放
- 如果不能：
    - 那就是这个项目中可能存在问题

**Comment by litcc** [comment]
日志中确实没看到有异常的地方，看时间应该是早上才把程序手动停止的，并不是自动停止的；需要麻烦你再多复现几次

**Comment by enterlet** [comment]
应该是MIUI的这个地方导致的
![Screenshot_2022-11-05-10-43-21-777_com miui powerkeeper](https://user-images.githubusercontent.com/21063655/200308045-8a3b66c4-2691-47d5-a540-e1c97fa47692.jpg)
关了试了两天了
看日志好像没有出现提早结束
