### ISSUE TITLE
请问能否增加GET方式？

### ISSUE THREAD

**Issue by Nannccyy** [litcc/tts-server#25]
想在其他程序里面使用，类似：
http://0.0.0.0/api/get?text=$TEXT&voiceName=zh-CN-XiaoxiaoNeural&voiceFormat=audio-24khz-96kbitrate-mono-mp3

**Comment by litcc** [comment]
get应该是支持的

**Comment by Nannccyy** [comment]
> get应该是支持的

是目前已经支持get方式，还是未来可以增加get方式？

**Comment by litcc** [comment]
目前是支持的

**Comment by litcc** [comment]
![image](https://github.com/litcc/tts-server/assets/13202561/1d3ee7af-2dce-4586-9158-71ea6ad5833b)

**Comment by litcc** [comment]
edge 免费接口参数支持较少，订阅的渠道可以配置更多的参数
