### ISSUE TITLE
可以加个web界面

### ISSUE THREAD

**Issue by ZYFDroid** [litcc/tts-server#4]
可以直接用这个

https://github.com/ZYFDroid/tts-server-frontend

![image](https://user-images.githubusercontent.com/39429452/157267114-ea34478c-8803-4213-b08e-0ac63a97254f.png)

下载https://github.com/ZYFDroid/tts-server-frontend/releases/tag/1.0.0.0
里的output.zip，然后把里面的文件挂在web服务里就行了

**Comment by litcc** [comment]
👍强，暂定周末把它加进去，周内有点忙

**Comment by ZYFDroid** [comment]
另外要不要顺便加一个获取发言人列表的api，以及获取合成风格（style）的api，我用fiddler看了下微软返回的json里是有相关数据的，还有中文名，地区等数据，可以试试弄成以下的格式
```
[
    {
        "displayname": "云希",
        "key": "zh-CN-YunxiNeural",
        "gender": "Male",
        "language": "zh-CN",
        "styles": [
            "narration-relaxed",
            "embarrassed",
            "fearful",
            "cheerful"
        ]
    },
    ...
]
```

**Comment by ZYFDroid** [comment]
可以用。不过如果你准备后期加入更多的语音合成api的话，就得进行加工

**Comment by litcc** [comment]
ok，那就再加工加工，我周天解决它。

**Comment by ZYFDroid** [comment]
先出新api吧，可以提前把webui的逻辑准备好，之后我会再把webui改改适配一下新api

**Comment by ptsa** [comment]
可以整合一个到docker 就好了， 我们用直接自动更新镜像就可以

**Comment by ZYFDroid** [comment]
> 可以整合一个到docker 就好了， 我们用直接自动更新镜像就可以

内置webui的话能方便普通用户的使用

**Comment by ptsa** [comment]
对，整合的话 用docker 部署会比较方便把

**Comment by litcc** [comment]
都可以实现，docker 容器这个就属于另外的需求了，你可以单独提个issue, 我会抽空搞的，我今天还 ** 的在加班，明天先把这个需求搞定，再处理 docker 容器

**Comment by ZYFDroid** [comment]
可惜我不会rust，不然我也能把这个弄出啦。（我只会C#和java，指针什么的绕不明白）

**Comment by litcc** [comment]
@ZYFDroid 看看这个数据能否满足需求 
https://raw.githubusercontent.com/litcc/tts-server/main/src/resource/api-list.json

**Comment by ZYFDroid** [comment]
我去下载最新构建看一下api的接口格式，等你看到tts-server-frontend有更新多半是稳了

**Comment by litcc** [comment]
目前只把 api 部分代码提交了上去，没有进行构建，因为 tts-server-frontend 还没有放进去

**Comment by ZYFDroid** [comment]
我正在手动构建，刚刚快速入门了一下cargo

**Comment by litcc** [comment]
ok,就用最新的 stable 就可以

**Comment by ZYFDroid** [comment]
api我已经弄明白了，这就去更新webui（只不过目前我还不怎么会用vue动态生成组件，只能先硬编码一下）

**Comment by ZYFDroid** [comment]
web ui 已适配 
https://github.com/ZYFDroid/tts-server-frontend/releases/tag/1.0.0.1

**Comment by litcc** [comment]
收到

**Comment by ZYFDroid** [comment]
昨天我自己试着研究了下把web ui往里面塞，然后发现serve静态文件还有点难度（对于我来说），至少不跟json文件一样。我有个想法，把静态文件打包成zip放进去，运行的时候就可以根据文件名查找（我有个软件就是这么干的）

**Comment by litcc** [comment]
这个web已经搞定了，现在在弄自动化构建

**Comment by ZYFDroid** [comment]
目前web资源嵌入到程序本体里还是放在外面的

**Comment by litcc** [comment]
内部的

**Comment by ptsa** [comment]
这次 没有自动 actions 么

**Comment by ptsa** [comment]
好像没有自动构建

**Comment by litcc** [comment]
不要急，yml还有点小问题，还在改，白天忙死了昨晚折腾到1:30还差点，耐心一点吧

**Comment by ZYFDroid** [comment]
> 好像没有自动构建

我手工构建了一下，目前windows可以构建，linux报错说event_bus的包有问题。你也可以手动下载tts-server-frontend的release然后把output.zip里的东西解压到web目录里进行构建
