### ISSUE TITLE
合成时中文句号没有停顿

### ISSUE THREAD

**Issue by ZYFDroid** [litcc/tts-server#5]

**Comment by litcc** [comment]
复现数据，以及复现场景

**Comment by ZYFDroid** [comment]
![image](https://user-images.githubusercontent.com/39429452/158064941-e9839264-55af-4593-b70a-c6c748bb8f45.png)

测试数据
```
这座宁静的小镇被葱绿的树木环绕，仿佛随时要被枝叶和藤蔓形成的翠绿波浪吞没。树叶在起风时沙沙作响，那声音像海潮，又像摇篮曲，笼罩着这座小镇和居住在镇上的人们。
```

似乎是微软的bug，但只要在句号后面加个空格就能解决问题。试试在替换标点的时候给英文标点后面都加一个空格

**Comment by ZYFDroid** [comment]
感觉在每个标点后面加空格之后停顿更自然一些
